# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import date
import requests
from requests.structures import CaseInsensitiveDict
import json


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Vertretungsplantool")
        MainWindow.resize(720, 420)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.switcher = QtWidgets.QTabWidget(self.centralwidget)
        self.switcher.setObjectName("switcher")
        self.inputpage = QtWidgets.QWidget()
        self.inputpage.setObjectName("inputpage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.inputpage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.inputpage)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.lineEdit = QtWidgets.QLineEdit(self.inputpage)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit, 0, QtCore.Qt.AlignTop)
        self.label_2 = QtWidgets.QLabel(self.inputpage)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignBottom)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.inputpage)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2, 0, QtCore.Qt.AlignTop)
        self.label_3 = QtWidgets.QLabel(self.inputpage)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignBottom)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.inputpage)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runbutton = QtWidgets.QPushButton(self.inputpage)
        self.runbutton.setObjectName("runbutton")
        self.horizontalLayout.addWidget(self.runbutton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.switcher.addTab(self.inputpage, "")
        self.outputpage = QtWidgets.QWidget()
        self.outputpage.setObjectName("outputpage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.outputpage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.outputpage)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.treeWidget = QtWidgets.QTreeWidget(self.outputpage)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Klasse")
        self.treeWidget.headerItem().setText(1, "Stunde")
        self.treeWidget.headerItem().setText(2, "Fach")
        self.treeWidget.headerItem().setText(3, "Raum")
        self.treeWidget.headerItem().setText(4, "Lehrer")
        self.treeWidget.headerItem().setText(5, "Text")
        self.verticalLayout_4.addWidget(self.treeWidget)
        self.switcher.addTab(self.outputpage, "")
        self.verticalLayout_2.addWidget(self.switcher)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.switcher.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Vertretungsplantool PyQt5 1", "Vertretungsplantool PyQt5 1"))
        self.label.setText(_translate("Vertretungsplantool PyQt5 1", "Tag, der nachzuschauen ist (0=Heute, 1=Morgen, 2=Übermorgen...)"))
        self.lineEdit.setText(_translate("Vertretungsplantool PyQt5 1", "1"))
        self.label_2.setText(_translate("Vertretungsplantool PyQt5 1", "Sollen nur Ausfälle angezeigt werden? (n = Nein,  j = Ja)"))
        self.lineEdit_2.setText(_translate("Vertretungsplantool PyQt5 1", "n"))
        self.label_3.setText(_translate("Vertretungsplantool PyQt5 1", "Nur Klasse/Jahrgang anzeigen (nichts oder wenn ja welche eingeben)"))
        self.runbutton.setText(_translate("Vertretungsplantool PyQt5 1", "Ausfüren"))
        self.runbutton.setShortcut(_translate("Vertretungsplantool PyQt5 1", "Ctrl+R"))
        self.switcher.setTabText(self.switcher.indexOf(self.inputpage), _translate("Vertretungsplantool PyQt5 1", "Eingabe"))
        self.label_4.setText(_translate("Vertretungsplantool PyQt5 1", "Wochentag"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        #self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.switcher.setTabText(self.switcher.indexOf(self.outputpage), _translate("Vertretungsplantool PyQt5 1", "Ausgabe"))

    def MyWorkingCode(self, MainWindow):
        from datetime import date
        print("asdfghjklöä")
        print(self.lineEdit.text())

        url = "https://nessa.webuntis.com/WebUntis/monitor/substitution/data?school=Gym%20Carolinum"

        date = date.today()
        date = date.strftime("%Y%m%d")

        def run():

            self.treeWidget.clear()

            headers = CaseInsensitiveDict()
            headers["Content-Type"] = "application/json"

            tage = self.lineEdit.text()

            nurAusfaelle = self.lineEdit_2.text().replace("j", "true").replace("n", "false")

            data = '"formatName":"VP SuS IServ morgen","schoolName":"Gym Carolinum","date":{},"dateOffset":{},"strikethrough":false,"mergeBlocks":true,"showOnlyFutureSub":false,"showBreakSupervisions":true,"showTeacher":true,"showClass":false,"showHour":true,"showInfo":true,"showRoom":true,"showSubject":true,"groupBy":1,"hideAbsent":false,"departmentIds":[],"departmentElementType":-1,"hideCancelWithSubstitution":true,"hideCancelCausedByEvent":false,"showTime":false,"showSubstText":true,"showAbsentElements":[],"showAffectedElements":[1],"showUnitTime":true,"showMessages":true,"showStudentgroup":false,"enableSubstitutionFrom":false,"showSubstitutionFrom":0,"showTeacherOnEvent":false,"showAbsentTeacher":true,"strikethroughAbsentTeacher":false,"activityTypeIds":[],"showEvent":true,"showCancel":true,"showOnlyCancel":{},"showSubstTypeColor":false,"showExamSupervision":false,"showUnheraldedExams":false'.format(
                date, tage, nurAusfaelle)
            data = "{" + data + "}"

            resp = requests.post(url, headers=headers, data=data)
            raw = resp.content.decode("utf-8")
            data = json.loads(raw)

            klasse = self.lineEdit_3.text()

            global outputline
            weekDay = data["payload"]["weekDay"]
            self.label_4.setText(weekDay)
            outputline = 0
            print("ok")
            self.switcher.setCurrentWidget(self.inputpage)
            for x in data['payload']['rows']:
                a = x['group']
                if klasse.upper() in a:
                    pass
                else:
                    continue

                c = [string.replace('<span class="substMonitorSubstElem">',"").replace("</span>", "") for string in x['data']]

                c.insert(0, a)
                print(c)

                global row
                row = 0
                item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
                for each in c:
                    self.treeWidget.topLevelItem(outputline).setText(row, str(each))
                    print(row, each)
                    row = row + 1

                outputline = outputline +1
            
            self.switcher.setCurrentIndex(1)



        self.runbutton.clicked.connect(run)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.MyWorkingCode(MainWindow)
    sys.exit(app.exec_())
